apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: todo-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: itheabhipatel/todo-backend-live:c955b8baf24ebbf837ba739d89199f8d6cae0e4a
          ports:
            - containerPort: 3100
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: mongo-secret