apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: todo-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: itheabhipatel/todo-backend-live:04e68d1865c9843ce79fa4dadcba16312df1dafe
          ports:
            - containerPort: 3100
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: mongo-secret