apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: todo-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: itheabhipatel/todo-backend-live:e0371f96f709d149b58a4b10862716d8f2fbb646
          ports:
            - containerPort: 3100
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: mongo-secret