apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: itheabhipatel/todo-frontend-live:c955b8baf24ebbf837ba739d89199f8d6cae0e4a
          ports:
            - containerPort: 80