apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: itheabhipatel/todo-frontend-live:04e68d1865c9843ce79fa4dadcba16312df1dafe
          ports:
            - containerPort: 80