apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: itheabhipatel/todo-frontend-live:e0371f96f709d149b58a4b10862716d8f2fbb646
          ports:
            - containerPort: 80