apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: todo-app
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: todoadmin
  MONGO_INITDB_ROOT_PASSWORD: change-this-strong-password
  MONGO_URI: mongodb://todoadmin:change-this-strong-password@mongo-service:27017/tododb?authSource=admin