---
- name: Configure k3s Kubernetes Server controller
  hosts: k3s_controller
  become: true


  vars_files:
    - secrets.yml
    
  vars:
    k3s_version: "v1.34.1+k3s1"
    kube_prometheus_stack_version: "87.18.0"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

  tasks:

    # --------------------------------------------------
    # System
    # --------------------------------------------------

    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - curl
          - git
          - apache2-utils
        state: present

    # --------------------------------------------------
    # k3s
    # --------------------------------------------------

    - name: Check if k3s is installed
      command: k3s --version
      register: k3s_check
      failed_when: false
      changed_when: false

    - name: Install k3s
      shell: |
        curl -sfL https://get.k3s.io | \
        INSTALL_K3S_VERSION="{{ k3s_version }}" \
        sh -s - --disable traefik --write-kubeconfig-mode 644
      when: k3s_check.rc != 0

    - name: Wait for Kubernetes node to be ready
      command: kubectl wait --for=condition=Ready node --all --timeout=300s
      changed_when: false

    - name: Get controller private IP
      set_fact:
        controller_private_ip: "{{ ansible_default_ipv4.address }}"

    - name: Get k3s node join token
      command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_join_token
      changed_when: false
      
    # --------------------------------------------------
    # Helm
    # --------------------------------------------------

    - name: Check if Helm is installed
      command: helm version
      register: helm_check
      failed_when: false
      changed_when: false

    - name: Install Helm
      shell: curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      when: helm_check.rc != 0

    # --------------------------------------------------
    # Helm Repositories
    # --------------------------------------------------

    - name: Add NGINX Ingress Helm repository
      command: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      register: nginx_repo
      failed_when: nginx_repo.rc != 0 and "already exists" not in nginx_repo.stderr
      changed_when: nginx_repo.rc == 0

    - name: Add Jetstack Helm repository
      command: helm repo add jetstack https://charts.jetstack.io
      register: jetstack_repo
      failed_when: jetstack_repo.rc != 0 and "already exists" not in jetstack_repo.stderr
      changed_when: jetstack_repo.rc == 0

    - name: Add Prometheus Helm repository
      command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      register: prometheus_repo
      failed_when: prometheus_repo.rc != 0 and "already exists" not in prometheus_repo.stderr
      changed_when: prometheus_repo.rc == 0

    - name: Add ArgoCD Helm repository
      command: helm repo add argo https://argoproj.github.io/argo-helm
      register: argo_repo
      failed_when: argo_repo.rc != 0 and "already exists" not in argo_repo.stderr
      changed_when: argo_repo.rc == 0

    - name: Update Helm repositories
      command: helm repo update
      changed_when: false

    # --------------------------------------------------
    # cert-manager
    # --------------------------------------------------

    - name: Install cert-manager
      command: >
        helm upgrade --install cert-manager jetstack/cert-manager
        --namespace cert-manager
        --create-namespace
        --set crds.enabled=true
        --wait
        --timeout 10m

    # --------------------------------------------------
    # Prometheus + Grafana
    # --------------------------------------------------
    - name: Copy Grafana Helm values
      copy:
        src: ../grafana/values.yaml
        dest: /tmp/grafana-values.yaml

    - name: Install Prometheus and Grafana
      command: >
        helm upgrade --install monitoring
        prometheus-community/kube-prometheus-stack
        --version {{ kube_prometheus_stack_version }}
        --namespace monitoring
        --create-namespace
        --values /tmp/grafana-values.yaml
        --set grafana.adminUser={{ grafana_admin_user }}
        --set-string grafana.adminPassword={{ grafana_admin_password }}
        --wait
        --timeout 15m

    # --------------------------------------------------
    # NGINX Ingress
    # --------------------------------------------------

    - name: Install NGINX Ingress
      command: >
        helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx
        --namespace ingress-nginx
        --create-namespace
        --set controller.metrics.enabled=true
        --set controller.metrics.serviceMonitor.enabled=true
        --set controller.metrics.serviceMonitor.additionalLabels.release=monitoring
        --wait
        --timeout 10m

    # --------------------------------------------------
    # Grafana Dashboards
    # --------------------------------------------------

    - name: Copy Grafana dashboards
      copy:
        src: ../grafana/dashboards/
        dest: /tmp/grafana-dashboards/

    - name: Create Server Health Grafana dashboard
      shell: |
        kubectl create configmap grafana-server-health \
          --namespace monitoring \
          --from-file=server-health.json=/tmp/grafana-dashboards/server-health.json \
          --dry-run=client -o yaml | kubectl apply -f -

        kubectl label configmap grafana-server-health \
          --namespace monitoring \
          grafana_dashboard=1 \
          --overwrite

    - name: Create Kubernetes Health Grafana dashboard
      shell: |
        kubectl create configmap grafana-kubernetes-health \
          --namespace monitoring \
          --from-file=kubernetes-health.json=/tmp/grafana-dashboards/kubernetes-health.json \
          --dry-run=client -o yaml | kubectl apply -f -

        kubectl label configmap grafana-kubernetes-health \
          --namespace monitoring \
          grafana_dashboard=1 \
          --overwrite

    - name: Create Traffic HTTP Grafana dashboard
      shell: |
        kubectl create configmap grafana-traffic-http \
          --namespace monitoring \
          --from-file=traffic-http.json=/tmp/grafana-dashboards/traffic-http.json \
          --dry-run=client -o yaml | kubectl apply -f -

        kubectl label configmap grafana-traffic-http \
          --namespace monitoring \
          grafana_dashboard=1 \
          --overwrite

    - name: Create Todo App Health Grafana dashboard
      shell: |
        kubectl create configmap grafana-todo-app-health \
          --namespace monitoring \
          --from-file=todo-app-health.json=/tmp/grafana-dashboards/todo-app-health.json \
          --dry-run=client -o yaml | kubectl apply -f -

        kubectl label configmap grafana-todo-app-health \
          --namespace monitoring \
          grafana_dashboard=1 \
          --overwrite

    # --------------------------------------------------
    # Controller Scheduling
    # --------------------------------------------------

    - name: Get controller node name
      command: kubectl get nodes -l node-role.kubernetes.io/control-plane=true -o jsonpath='{.items[0].metadata.name}'
      register: controller_node_name
      changed_when: false

    - name: Prevent workloads from running on controller
      command: >
        kubectl taint nodes
        {{ controller_node_name.stdout }}
        node-role.kubernetes.io/control-plane=true:NoSchedule
      register: taint_result
      failed_when: false
      changed_when: "'tainted' in taint_result.stdout"
  
