---
- name: Configure k3s Workers
  hosts: k3s_workers
  become: true

  vars:
    k3s_version: "v1.34.1+k3s1"

  tasks:

    # --------------------------------------------------
    # System
    # --------------------------------------------------

    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - curl
        state: present

    # --------------------------------------------------
    # k3s Agent
    # --------------------------------------------------

    - name: Check if k3s agent is installed
      command: k3s-agent --version
      register: k3s_agent_check
      failed_when: false
      changed_when: false

    - name: Install and join k3s worker
      shell: |
        curl -sfL https://get.k3s.io | \
        INSTALL_K3S_VERSION="{{ k3s_version }}" \
        K3S_URL="https://{{ hostvars[groups['k3s_controller'][0]].controller_private_ip }}:6443" \
        K3S_TOKEN="{{ hostvars[groups['k3s_controller'][0]].k3s_join_token.stdout }}" \
        sh -
      when: k3s_agent_check.rc != 0

    # --------------------------------------------------
    # Wait
    # --------------------------------------------------

    - name: Wait for k3s agent service
      service:
        name: k3s-agent
        state: started
        enabled: true

    # --------------------------------------------------
    # Verify
    # --------------------------------------------------

    - name: Wait for worker node to join
      pause:
        seconds: 15

- name: Verify Kubernetes Cluster
  hosts: k3s_controller
  become: true

  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

  tasks:

    - name: Get Kubernetes nodes
      command: kubectl get nodes
      register: nodes
      changed_when: false

    - name: Show Kubernetes nodes
      debug:
        var: nodes.stdout_lines